### PR TITLE
Working Apple universal plugin (Intel/ARM) with full metal acceleration

### PR DESCRIPTION
**Pull request by eltorio**
Thanks Stefan for your work, I can now use my GoPro Max with Davinci Resolve under MacOS.

### CODE REVIEW

**Comment by stefsietz** [comment]
Hi Ronan, thanks for your great work! Would it be possible for you to resolve the merge conflicts?

**Comment by sgravel-dev** [comment]
@stefsietz I notice the merge includes changes I made in my fork, including renaming the plugin to `Reframe360 XL`.  I did that as I added features which might be a departure from your original intent and I was under the impression you did not want to maintain this project.  At this point I only added animation curves so it's not too bad but I'm reconsidering having a totally separate project.

What do you think?

**Comment by stefsietz** [comment]
@LRP-sgravel Oh yeah I missed that. So now the readme is a bit misleading :-D
Probably makes sense if I point to your repo in the Readme, so that interested contriubtors can fork from your better maintained project.
Thanks a lot for keeping this alive, never would have imagined that happening. Gotta get out my Gopro Fusion again some time and record some footage to check out your features.

**Comment by sgravel-dev** [comment]
Hello Stefan, you can definitely point to my repo if you’d like.  I’m not guaranteeing much maintenance but I’ll be adding stuff for my own needs and I’ll release it when adding new features and bugfixes.

Thanks for your original work on this.

**Pull request merged**
