### PR TITLE
Build on MacOS

### PR DESCRIPTION
**Pull request by eltorio**
Hi Stefan,
Thanks for your work.
I build it under MacOS with OpenCL kernel. If if I take enough time. I'll look the Metal kernel.
Ronan

### CODE REVIEW

**Comment by sgravel-dev** [comment]
@eltorio I've also been working on this plugin to fix bugs and add features.  Would it be better to merge your PR in my repo?

https://github.com/LRP-sgravel/reframe360XL

**Comment by eltorio** [comment]
@LRP-sgravel no pb, I'll check if an automatic merge can be done.
Did you take a look on the Metal kernel, or you only use Cuda?

**Comment by sgravel-dev** [comment]
I did not look into Mac yet at all.  I was wondering if I should this morning actually.

I doubt an automatic merge will be doable. I changed a few parameter in the project settings when figuring out how to compile it, including paths to GLM and such.

**Comment by sgravel-dev** [comment]
Ok I see you almost only modified the makefile, the merge should be fine.

**Comment by eltorio** [comment]
Some other small things 
I don't know how to change the based repo where mine is forked,
I manually integrate the change into another clone
this is the difff with yours
[patch-2a30c11.txt](https://github.com/stefsietz/reframe360resolve/files/6336066/patch-2a30c11.txt)

**Comment by sgravel-dev** [comment]
Will check it out later.

Thanks

**Comment by stefsietz** [comment]
awesome, thanks!

**Comment by sgravel-dev** [comment]
Merged in my fork and tested.  Thanks.  I might look into Metal next.

**Comment by eltorio** [comment]
Working Metal version in my fork
😂

**Comment by sgravel-dev** [comment]
I'll take it .  Thanks

**Pull request merged**
